### ISSUE TITLE
Application crashes when adding aurelia-validation to it

### ISSUE THREAD

**Issue by nseba** [aurelia/validation#108]
I've installed the validation plugin as described in the doc. In the moment I add the .plugin('aurelia-validation') to the aurelia main file, the application crashes with the following stack trace:
`
Unhandled promise rejection Error: Error instantiating undefined.
------------------------------------------------
inner error: TypeError: [object Object] is not a function!
    at TypeError (native)
    at Function.assert.fn (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.assert.js:10:24)
    at Object.construct (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.reflect.js:45:24)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/metadata.js:183:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:198:35)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
------------------------------------------------
inner error: TypeError: [object Object] is not a function!
    at TypeError (native)
    at Function.assert.fn (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.assert.js:10:24)
    at Object.construct (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.reflect.js:45:24)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/metadata.js:183:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:198:35)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at AggregateError (http://localhost:9000/jspm_packages/github/aurelia/logging@0.4.0/index.js:24:15)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:200:19)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at HtmlBehaviorResource.analyze (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:2500:40)
    at ResourceModule.analyze (http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/module-analyzer.js:68:24)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/view-engine.js:134:24(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31
es6.promise.js:139 Unhandled promise rejection Error: Error instantiating undefined.
------------------------------------------------
inner error: TypeError: [object Object] is not a function!
    at TypeError (native)
    at Function.assert.fn (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.assert.js:10:24)
    at Object.construct (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.reflect.js:45:24)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/metadata.js:183:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:198:35)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
------------------------------------------------
inner error: TypeError: [object Object] is not a function!
    at TypeError (native)
    at Function.assert.fn (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/$.assert.js:10:24)
    at Object.construct (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.reflect.js:45:24)
    at ClassActivator.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/metadata.js:183:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:198:35)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at AggregateError (http://localhost:9000/jspm_packages/github/aurelia/logging@0.4.0/index.js:24:15)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:200:19)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
    at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
    at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
    at HtmlBehaviorResource.analyze (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.16/aurelia-templating.js:2500:40)
    at ResourceModule.analyze (http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/module-analyzer.js:68:24)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/view-engine.js:134:24
`

**Comment by nseba** [comment]
Here is my config.js:

System.config({
  "transpiler": "traceur",
  "paths": {
    "*": "wwwroot/*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "aurelia-skeleton-navigation/*": "wwwroot/app/*.js",
    "bower:*": "jspm_packages/bower/*.js"
  }
});

System.config({
  "map": {
    "aurelia-animator-css": "github:aurelia/animator-css@0.2.0",
    "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.12.0",
    "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.7.1",
    "aurelia-framework": "github:aurelia/framework@0.14.1",
    "aurelia-http-client": "github:aurelia/http-client@0.10.3",
    "aurelia-router": "github:aurelia/router@0.10.4",
    "aurelia-templating": "github:aurelia/templating@0.8.14",
    "aurelia-validation": "github:aurelia/validation@0.2.7",
    "babel": "npm:babel-core@5.1.13",
    "babel-runtime": "npm:babel-runtime@5.1.13",
    "bootstrap": "github:twbs/bootstrap@3.3.4",
    "core-js": "npm:core-js@1.0.1",
    "css": "github:systemjs/plugin-css@0.1.13",
    "font-awesome": "npm:font-awesome@4.4.0",
    "jquery": "github:components/jquery@2.1.4",
    "traceur": "github:jmcriffey/bower-traceur@0.0.88",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.88",
    "github:aurelia/animator-css@0.2.0": {
      "aurelia-templating": "github:aurelia/templating@0.11.2"
    },
    "github:aurelia/binding@0.3.7": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
      "aurelia-metadata": "github:aurelia/metadata@0.3.4",
      "aurelia-task-queue": "github:aurelia/task-queue@0.2.5"
    },
    "github:aurelia/binding@0.6.1": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.7.1",
      "aurelia-metadata": "github:aurelia/metadata@0.5.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.4.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/binding@0.8.6": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/bootstrapper@0.12.0": {
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.4.0",
      "aurelia-framework": "github:aurelia/framework@0.11.0",
      "aurelia-history": "github:aurelia/history@0.4.0",
      "aurelia-history-browser": "github:aurelia/history-browser@0.4.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.7.0",
      "aurelia-logging-console": "github:aurelia/logging-console@0.4.0",
      "aurelia-router": "github:aurelia/router@0.8.1",
      "aurelia-templating": "github:aurelia/templating@0.11.2",
      "aurelia-templating-binding": "github:aurelia/templating-binding@0.11.0",
      "aurelia-templating-resources": "github:aurelia/templating-resources@0.11.1",
      "aurelia-templating-router": "github:aurelia/templating-router@0.12.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/dependency-injection@0.4.5": {
      "aurelia-metadata": "github:aurelia/metadata@0.3.4",
      "core-js": "npm:core-js@0.4.10"
    },
    "github:aurelia/dependency-injection@0.7.1": {
      "aurelia-logging": "github:aurelia/logging@0.4.0",
      "aurelia-metadata": "github:aurelia/metadata@0.5.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/dependency-injection@0.9.2": {
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/event-aggregator@0.6.2": {
      "aurelia-logging": "github:aurelia/logging@0.6.4"
    },
    "github:aurelia/framework@0.11.0": {
      "aurelia-binding": "github:aurelia/binding@0.6.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.7.1",
      "aurelia-loader": "github:aurelia/loader@0.6.0",
      "aurelia-logging": "github:aurelia/logging@0.4.0",
      "aurelia-metadata": "github:aurelia/metadata@0.5.0",
      "aurelia-path": "github:aurelia/path@0.6.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.4.0",
      "aurelia-templating": "github:aurelia/templating@0.11.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/framework@0.14.1": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "aurelia-templating": "github:aurelia/templating@0.13.16",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/history-browser@0.4.0": {
      "aurelia-history": "github:aurelia/history@0.4.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/http-client@0.10.3": {
      "aurelia-path": "github:aurelia/path@0.8.1",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/loader-default@0.7.0": {
      "aurelia-loader": "github:aurelia/loader@0.6.0",
      "aurelia-metadata": "github:aurelia/metadata@0.5.0"
    },
    "github:aurelia/loader@0.3.5": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.1.3",
      "core-js": "npm:core-js@0.4.10",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.5.5"
    },
    "github:aurelia/loader@0.6.0": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-path": "github:aurelia/path@0.6.1",
      "core-js": "npm:core-js@0.9.18",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.3"
    },
    "github:aurelia/loader@0.8.7": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "core-js": "npm:core-js@0.9.18",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.3"
    },
    "github:aurelia/metadata@0.5.0": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/metadata@0.7.3": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/route-recognizer@0.4.0": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/route-recognizer@0.6.2": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/router@0.10.4": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.6.2",
      "aurelia-history": "github:aurelia/history@0.6.1",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/router@0.8.1": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.7.1",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.4.0",
      "aurelia-history": "github:aurelia/history@0.4.0",
      "aurelia-path": "github:aurelia/path@0.6.1",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.4.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-binding@0.11.0": {
      "aurelia-binding": "github:aurelia/binding@0.6.1",
      "aurelia-logging": "github:aurelia/logging@0.4.0",
      "aurelia-templating": "github:aurelia/templating@0.11.2"
    },
    "github:aurelia/templating-resources@0.11.1": {
      "aurelia-binding": "github:aurelia/binding@0.6.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.7.1",
      "aurelia-logging": "github:aurelia/logging@0.4.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.4.0",
      "aurelia-templating": "github:aurelia/templating@0.11.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-router@0.12.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.7.1",
      "aurelia-metadata": "github:aurelia/metadata@0.5.0",
      "aurelia-path": "github:aurelia/path@0.6.1",
      "aurelia-router": "github:aurelia/router@0.8.1",
      "aurelia-templating": "github:aurelia/templating@0.11.2"
    },
    "github:aurelia/templating@0.11.2": {
      "aurelia-binding": "github:aurelia/binding@0.6.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.7.1",
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-loader": "github:aurelia/loader@0.6.0",
      "aurelia-logging": "github:aurelia/logging@0.4.0",
      "aurelia-metadata": "github:aurelia/metadata@0.5.0",
      "aurelia-path": "github:aurelia/path@0.6.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.4.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating@0.13.16": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating@0.8.14": {
      "aurelia-binding": "github:aurelia/binding@0.3.7",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.4.5",
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.1.3",
      "aurelia-loader": "github:aurelia/loader@0.3.5",
      "aurelia-logging": "github:aurelia/logging@0.2.7",
      "aurelia-metadata": "github:aurelia/metadata@0.3.4",
      "aurelia-path": "github:aurelia/path@0.4.6",
      "aurelia-task-queue": "github:aurelia/task-queue@0.2.5",
      "core-js": "npm:core-js@0.4.10"
    },
    "github:aurelia/validation@0.2.7": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-templating": "github:aurelia/templating@0.13.16"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:twbs/bootstrap@3.3.4": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "npm:core-js@0.4.10": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:font-awesome@4.4.0": {
      "css": "github:systemjs/plugin-css@0.1.13"
    }
  }
});

**Comment by PWKad** [comment]
@nseba Can you please verify this is on the latest releases?  If not closing this issue.
