### ISSUE TITLE
Bind to child property fails when extracting bootstrap markup

### ISSUE THREAD

**Issue by philiphendry** [aurelia/validation#113]
I have a details page that looks like this:

```
<template>
        <form role="form" class="form-horizontal" validate.bind="validation">
            <!-- <control-textbox label="Event Name" value.bind="event.name" /> -->
            <div class="form-group">
                <label class="col-sm-2 control-label">Event Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" value.bind="event.name">
                </div>
            </div>
        </form>
</template>
```

with the view mode:

```
import {inject, bindable} from "aurelia-framework";
import {Validation} from "aurelia-validation";

@inject(Validation)
export class EventDetail {
	constructor(validation) {
		this.validation = validation.on(this)
			.ensure("event.name").isNotEmpty();
	}
	activate(params) {
		this.event = { name: "Event Name" };
	}
}
```

and this works fine. However, if I swap the bootstrap markup in the template for the `<control-textbox />` which is defined as this:

```
<template>
    <div class="row">
        <div class="form-group">
            <label class="col-sm-2 control-label">${label}</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" value.bind="value">
            </div>
        </div>
    </div>
</template>
```

and

```
import {customElement, bindable} from "aurelia-framework";

@customElement("control-textbox")
export class TextBoxCustomElement {
	@bindable label;
	@bindable value;
}
```

Then it fails with the following:

```
ERROR [app-router] TypeError: Cannot read property 'classList' of null
    at TWBootstrapViewStrategy.searchFormGroup (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute-view-strategy.js:66:25)
    at TWBootstrapViewStrategy.searchFormGroup (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute-view-strategy.js:69:19)
    at TWBootstrapViewStrategy.searchFormGroup (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute-view-strategy.js:69:19)
    at TWBootstrapViewStrategy.searchFormGroup (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute-view-strategy.js:69:19)
    at TWBootstrapViewStrategy.searchFormGroup (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute-view-strategy.js:69:19)
    at TWBootstrapViewStrategy.appendUIVisuals (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute-view-strategy.js:116:28)
    at TWBootstrapViewStrategy.prepareElement (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute-view-strategy.js:144:12)
    at ValidateCustomAttribute.subscribeChangedHandlers (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute.js:36:27)
    at ValidateCustomAttribute.subscribeChangedHandlers (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute.js:43:14)
    at ValidateCustomAttribute.valueChanged (http://127.0.0.1:8080/jspm_packages/github/aurelia/validation@0.2.7/validation/validate-custom-attribute.js:26:14)
```

Interestingly, this doesn't happen if I'm binding to `this.name` rather than `this.event.name`.

**Comment by philiphendry** [comment]
Just a thought, but I presume that the searchFormGroup is traversing up the element hierarchy to find a location (the element with a `form-group` css class) to inject the validation messages and that this is happening before the `<control-textbox/>` html template has had a chance to be included in the DOM? I've noticed that this is the same message I get if I purposefully mis-type the `form-group` css class.

**Comment by PWKad** [comment]
This is due to validation defaulting to Bootstrap when looking for classes.  This will be addressed in the refactor towards templating validation but I'll open a reference issue there to ensure someone notifies you when that work is complete.
