### ISSUE TITLE
@bindable with validation throws error

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/validation#130]
This error is thrown if you use validation on a @bindable property:

```
Unhandled promise rejection TypeError: Cannot read property 'message' of null
    at BindableProperty.initialize (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:2448:33)
    at new BehaviorInstance (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:2199:23)
    at HtmlBehaviorResource.create (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:2821:30)
    at https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:3385:27
    at f (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)
    at q (https://cdn.rawgit.com/jdanyow/aurelia-plunker/v0.4.0/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1600:11)
```

plunkr is here: http://plnkr.co/edit/kY7ZND?p=preview

**Comment by janvanderhaegen** [comment]
Grrrrr, we had this bug fixed earlier :O

Will see why it's back and the tests are still failing :(

**Comment by JeroenVinke** [comment]
I think that the tests may be failing because you forgot to hit the merge button here: https://github.com/aurelia/validation/pull/121 :smile:

**Comment by janvanderhaegen** [comment]
OMGOMGOMG

**Comment by janvanderhaegen** [comment]
Reopened, let's double check first ;-) But #121 is merged now :)

**Comment by JeroenVinke** [comment]
Also, if you're getting the `define is not defined` error when running tests, it's because of this: https://github.com/aurelia/validation/pull/127

**Comment by JeroenVinke** [comment]
This may be caused by this: https://github.com/aurelia/templating/issues/152, and there's a fix: https://github.com/PWKad/templating/commit/d3e990be5b52cc44c58c6ee4a32ba458d7e00ecc but hasn't been released yet. I suggest we wait

**Comment by JeroenVinke** [comment]
yep, this is not related to aurelia-validation
