### ISSUE TITLE
Inner error when injecting ValidationConfig

### ISSUE THREAD

**Issue by valichek** [aurelia/validation#197]
I need to switch locale globally, but cannot access ValidationConfig.

Anywhere, app.js or any component, when injecting ValidationConfig I get inner error.
But,
```javascript
import {ValidationConfig} from 'aurelia-validation';
console.log('ValidationConfig', ValidationConfig); // => function ValidationConfig()
```

I think the same issue here: http://aurelia.io/validation/#/i18n (errors in console)
```
Error: Error invoking undefined. Check the inner error for details.
------------------------------------------------
inner error: TypeError: Type is not a function
    at Object.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:334:14)
    at InvocationHandler.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at StrategyResolver.get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
    at Container._get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:508:23)
    at Container._get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:505:28)
    at Container.get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:491:28)
    at Container.elementContainerGet [as get] (http://localhost:3030/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.1/aurelia-templating.js:1504:17)
    at Object.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:349:81)
    at InvocationHandler.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Object.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:334:14)
    at InvocationHandler.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at StrategyResolver.get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
    at Container._get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:508:23)
    at Container._get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:505:28)
    at Container.get (http://localhost:3030/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:491:28)
...
```

**Comment by kdeberni** [comment]
@valichek I was just about to open new issue with d.ts file and I saw your issue. I am switching validation locale globally with Validation class. I am injecting Validation class and then on validationInstance is property config:ValidationConfig where you can switch locale.
I am not sure if this is proper so somebody here could confirm or denie it.

**Comment by valichek** [comment]
@kdeberni , thx, will try

**Comment by PWKad** [comment]
@valichek @kdeberni Yes I think this is the proper way to change the locale, if that isn't working please feel free to open this back up and we can figure out the right way.

In the end we need to get the locale setup out of validation anyway :)  That is tracking in #174
