### ISSUE TITLE
Validation not working. "aurelia-validation": "npm:aurelia-validation@0.6.3",

### ISSUE THREAD

**Issue by vdangwal** [aurelia/validation#222]
constructor(
        private validation: Validation) {
this.validation.on(this)
            .ensure('currentSearchCriteria.firstName').isNotEmpty()
            .hasMinLength(3);
}

HTML:
<form class="col s12" validate.bind="validation" >
Main.ts:
.plugin('aurelia-validation');

Still getting below exception. 

ERROR [app-router] TypeError: Cannot read property 'properties' of undefined
    at TWBootstrapViewStrategyBase.getValidationProperty (http://localhost:9000/jspm_packages/npm/aurelia-validation@0.6.3/validation-view-strategy.js:28:49)
    at ValidateCustomAttribute.subscribeChangedHandlers (http://localhost:9000/jspm_packages/npm/aurelia-validation@0.6.3/validate-custom-attribute.js:33:45)
    at ValidateCustomAttribute.subscribeChangedHandlers (http://localhost:9000/jspm_packages/npm/aurelia-validation@0.6.3/validate-custom-attribute.js:43:14)
    at ValidateCustomAttribute.subscribeChangedHandlers (http://localhost:9000/jspm_packages/npm/aurelia-validation@0.6.3/validate-custom-attribute.js:43:14)
    at ValidateCustomAttribute.subscribeChangedHandlers (http://localhost:9000/jspm_packages/npm/aurelia-validation@0.6.3/validate-custom-attribute.js:43:14)
    at ValidateCustomAttribute.valueChanged (http://localhost:9000/jspm_packages/npm/aurelia-validation@0.6.3/validate-custom-attribute.js:24:14)
    at BehaviorPropertyObserver.selfSubscriber (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:3188:48)
    at BehaviorPropertyObserver.call (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:3055:14)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:2919:18)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1010:24)

**Comment by vdangwal** [comment]
I think i found the issue. I was having wrong code which was causing the issues. Thus closing this issue.,
