### ISSUE TITLE
Uncaught (in promise) Error: Error invoking SVGAnalyzer. Check the inner error for details.

### ISSUE THREAD

**Issue by fabiomdf** [aurelia/validation#231]
**I did the download and installation of aurelia-validation@0.6.6**
**after configure the application plugin:**

```
export function configure(aurelia){

    aurelia.use
           .standardConfiguration()
           .developmentLogging()
           .plugin("aurelia-validation");

    aurelia.start().then(a => a.setRoot('app', document.body));

};
```

**it shows me this error**

**what am I doing wrong? :(**

aurelia-pal.js:20 Uncaught (in promise) Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
inner error: TypeError: _aureliaPal.DOM.createElement is not a function
    at createElement (http://localhost:54141/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:4391:31)
    at new SVGAnalyzer (http://localhost:54141/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:4400:11)
    at Object.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:364:14)
    at InvocationHandler.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:339:168)
    at Container.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:587:25)
    at StrategyResolver.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:145:37)
    at Container.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:518:41)
    at Object.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:389:105)
    at InvocationHandler.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:339:168)
    at Container.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:587:25)
    at createElement (http://localhost:54141/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:4391:31)
    at new SVGAnalyzer (http://localhost:54141/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:4400:11)
    at Object.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:364:14)
    at InvocationHandler.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:339:168)
    at Container.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:587:25)
    at StrategyResolver.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:145:37)
    at Container.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:518:41)
    at Object.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:389:105)
    at InvocationHandler.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:339:168)
    at Container.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:587:25)
    at new AggregateError (http://localhost:54141/jspm_packages/npm/aurelia-pal@1.0.0-beta.1.1.1/aurelia-pal.js:20:13)
    at Container.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:589:15)
    at StrategyResolver.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:145:37)
    at Container.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:518:41)
    at Object.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:389:105)
    at InvocationHandler.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:339:168)
    at Container.invoke (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:587:25)
    at StrategyResolver.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:145:37)
    at Container.get (http://localhost:54141/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:518:41)
    at HtmlBehaviorResource.initialize (http://localhost:54141/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:3252:40)AggregateError @ aurelia-pal.js:20invoke @ aurelia-dependency-injection.js:589get @ aurelia-dependency-injection.js:145get @ aurelia-dependency-injection.js:518invoke @ aurelia-dependency-injection.js:389invoke @ aurelia-dependency-injection.js:339invoke @ aurelia-dependency-injection.js:587get @ aurelia-dependency-injection.js:145get @ aurelia-dependency-injection.js:518initialize @ aurelia-templating.js:3252initialize @ aurelia-templating.js:2515initialize @ aurelia-templating.js:2434(anonymous function) @ aurelia-templating.js:2795

**Comment by jdanyow** [comment]
do you have any forks? `jspm inspect --forks`

**Comment by fabiomdf** [comment]
npm:aurelia-binding 1.0.0-beta.1.2.2 1.0.0-beta.1.3.0
npm:aurelia-dependency-injection 1.0.0-beta.1.1.5 1.0.0-beta.1.2.0
npm:aurelia-loader 1.0.0-beta.1.1.1 1.0.0-beta.1.2.0
npm:aurelia-logging 1.0.0-beta.1.1.2 1.0.0-beta.1.2.0
npm:aurelia-metadata 1.0.0-beta.1.1.6 1.0.0-beta.1.2.0
npm:aurelia-pal 1.0.0-beta.1.1.1 1.0.0-beta.1.2.0
npm:aurelia-path 1.0.0-beta.1.1.1 1.0.0-beta.1.2.0
npm:aurelia-task-queue 1.0.0-beta.1.1.1 1.0.0-beta.1.2.0
npm:aurelia-templating 1.0.0-beta.1.1.4 1.0.0-beta.1.2.0

**Comment by jdanyow** [comment]
k you'll need to `jspm install` each of these to clean up the forks... eg `jspm install aurelia-binding` and so on.

**Comment by fabiomdf** [comment]
I did it, but unfortunately the error is still there.

**Comment by doktordirk** [comment]
gulp unbundle (just a guess)

else rebuild the config (@jdanyow i'd lke to see a task for that. i'm getting tired of explaining howto)
* delete the jspm folder
* delete the map entry in config js
* run jspm install

**Comment by jdanyow** [comment]
@fabiomdf let us know if @doktordirk's steps solve your issue

**Comment by fabiomdf** [comment]
Now it's working. I did exactly what @doktordirk said. Thank you guys very much.

**Comment by jdanyow** [comment]
:+1:

**Comment by ams3cf** [comment]
For those that got here via Google - I ran across the same issue after installing aurelia-dialog; following   the instructions from @doktordirk resolved the issue for me as well.

**Comment by danielabar** [comment]
I'm getting the same error using webpack, trying to use `@bindable foo` in a custom element. Tried deleting node_modules folder and re-installing latest rc versions of all the aurelia libraries but still same error.  

If I put a breakpoint at aurelia-binding line 4418 and step into `_aureliaPal.DOM.createElement` that function is defined and seems to run through successfully, but then letting it continue on, still get the stack trace:

```
aurelia-logging-console.js:54 ERROR [app-router] Error: Error invoking SVGAnalyzer. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: _aureliaPal.DOM.createElement is not a function
Inner Error Stack:
TypeError: _aureliaPal.DOM.createElement is not a function
    at createElement (webpack:////Users/dbaron/projects/flute-ui-histogram-component/~/aurelia-binding/dist/commonjs/aurelia-binding.js?:4418:29)
    at new SVGAnalyzer (webpack:////Users/dbaron/projects/flute-ui-histogram-component/~/aurelia-binding/dist/commonjs/aurelia-binding.js?:4427:9)
    at Object.invoke (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:337:12)
    at InvocationHandler.invoke (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:314:166)
    at Container.invoke (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:576:23)
    at StrategyResolver.get (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:126:35)
    at Container.get (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:507:39)
    at Object.invoke (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:367:103)
    at InvocationHandler.invoke (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:314:166)
    at Container.invoke (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:576:23)
    at StrategyResolver.get (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:126:35)
    at Container.get (webpack:///../~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:507:39)
    at HtmlBehaviorResource.initialize (webpack:////Users/dbaron/projects/flute-ui-histogram-component/~/aurelia-templating/dist/commonjs/aurelia-templating.js?:3775:38)
    at ResourceDescription.initialize (webpack:///../~/aurelia-templating/dist/commonjs/aurelia-templating.js?:2930:19)
    at ResourceModule.initialize (webpack:///../~/aurelia-templating/dist/commonjs/aurelia-templating.js?:2850:15)
    at eval (webpack:///../~/aurelia-templating/dist/commonjs/aurelia-templating.js?:3208:18)
    at tryCatcher (webpack:///../~/bluebird/js/browser/bluebird.js?:5098:23)
    at Promise._settlePromiseFromHandler (webpack:///../~/bluebird/js/browser/bluebird.js?:3129:31)
    at Promise._settlePromise (webpack:///../~/bluebird/js/browser/bluebird.js?:3186:18)
    at Promise._settlePromise0 (webpack:///../~/bluebird/js/browser/bluebird.js?:3231:10)
    at Promise._settlePromises (webpack:///../~/bluebird/js/browser/bluebird.js?:3310:18)
    at Promise._fulfill (webpack:///../~/bluebird/js/browser/bluebird.js?:3255:18)
End Inner Error Stack
```

package.json is:

```
"dependencies": {
    "aurelia-bootstrapper-webpack": "^1.0.0-rc.1.0.0",
    "aurelia-event-aggregator": "^1.0.0-rc.1.0.0",
    "aurelia-fetch-client": "^1.0.0-rc.1.0.1",
    "aurelia-framework": "^1.0.0-rc.1.0.2",
    "aurelia-history-browser": "^1.0.0-rc.1.0.0",
    "aurelia-logging-console": "^1.0.0-rc.1.0.0",
    "aurelia-pal-browser": "^1.0.0-rc.1.0.1",
    "aurelia-polyfills": "^1.0.0-rc.1.0.0",
    "aurelia-route-recognizer": "^1.0.0-rc.1.0.1",
    "aurelia-router": "^1.0.0-rc.1.0.1",
    "aurelia-templating-binding": "^1.0.0-rc.1.0.1",
    "aurelia-templating-resources": "^1.0.0-rc.1.0.1",
    "aurelia-templating-router": "^1.0.0-rc.1.0.1",
    "aurelia-validation": "0.8.1",
    "babel-plugin-transform-runtime": "6.7.5",
    "babel-runtime": "5.8.38",
    "bluebird": "3.3.5",
    "bootstrap": "3.3.6",
    "d3": "4.1.1",
    "exports-loader": "0.6.3",
    "font-awesome": "4.6.1",
    "imports-loader": "0.6.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "2.2.3",
    "lodash": "4.11.1",
    "moment": "2.13.0",
    "whatwg-fetch": "1.0.0"
  }
```

**Comment by jszpila** [comment]
I've also run in to this issue when using aurelia-framework@1.0.0-rc.1.0.0 and installing aurelia-validatejs@0.7.0 and @doktordirk's instructions did not resolve the issue. Any other ideas on what I can do?

**Comment by doktordirk** [comment]
do you have any forks? jspm inspect --forks

**Comment by jszpila** [comment]
@doktordirk - thanks for the quick response. I have the following forks:

npm:aurelia-binding 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-dependency-injection 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-loader 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-logging 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-metadata 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-pal 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-path 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-task-queue 1.0.0-rc.1.0.0 1.0.0
npm:aurelia-templating 1.0.0-rc.1.0.0 1.0.0

I installed them per @jdanyow's instructions above the I still get the error, both before and after following your steps again.

I guess one question I should ask is when you refer say "delete the jspm folder" do you mean the jspm_packages folder or another folder (I have jspm_packages/github/jspm and node_modules/jspm)?

**Comment by doktordirk** [comment]
the whole ./jspm_packages folder. but maybe just try jspm update -a first

**Comment by jszpila** [comment]
Thanks, jspm update seems to have resolved the issue.
