### ISSUE TITLE
Error on  aurelia-validation module

### ISSUE THREAD

**Issue by luisdav86** [aurelia/validation#249]
I'm trying to use   aurelia-validation but it show me this error, when the component is loading. It looks like it can't find the module to injected it.

	aurelia-logging-console.js:58 ERROR [app-router] Error: Error invoking EditItem. Check the inner error for details.
	------------------------------------------------
	Inner Error:
	Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
	Inner Error Stack:
	Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
		at Container.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:480:15)
		at Object.invoke (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:329:33)
		at InvocationHandler.invoke (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:300:168)
		at Container.invoke (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:564:25)
		at StrategyResolver.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:127:37)
		at Container.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:501:23)
		at eval (http://localhost:58085/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:3925:73)
	End Inner Error Stack
	------------------------------------------------

		at Container.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:480:15)
		at Object.invoke (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:329:33)
		at InvocationHandler.invoke (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:300:168)
		at Container.invoke (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:564:25)
		at StrategyResolver.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:127:37)
		at Container.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:501:23)
		at eval (http://localhost:58085/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:3925:73)
	End Inner Error Stack
	------------------------------------------------

		at new AggregateError (http://localhost:58085/jspm_packages/npm/aurelia-pal@1.0.0-beta.1.2.2/aurelia-pal.js:38:13)
		at Container.invoke (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:566:15)
		at StrategyResolver.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:127:37)
		at Container.get (http://localhost:58085/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.2.3/aurelia-dependency-injection.js:501:23)
		at eval (http://localhost:58085/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:3925:73)
This is my component 

    import {Validation} from 'aurelia-validation';

    export class EditItem  {
        static inject() { return [Validation];}

        constructor(validation) {
            console.log(validation)       
        }  
    }

And this is my main.js

    export function configure(aurelia){
        aurelia.use
               .standardConfiguration()
               .developmentLogging()           
               .plugin('aurelia-validation')
               .plugin('aurelia-kendoui-bridge', (kendo) => kendo.pro());
           

        aurelia.start().then(a=> a.setRoot());

    };

My index.html has this code

    <body aurelia-app="main">  

Do you have any idea what do I need to change?

**Comment by blandau** [comment]
I'm encountering the same error. I did a quick scan through the other Aurelia repos and found https://github.com/aurelia/validatejs. This may be the correct Aurelia validation library but I welcome and wait for the official word.

**Comment by EisenbergEffect** [comment]
Yes, validatejs is the validation library. This library contains only "interfaces" for pluggable validation systems. The validation mechanism for Aurelia is in flux now since we are working on a new design. It should stabilize in the next couple of weeks.

**Comment by luisdav86** [comment]
Thanks. I will work with validatejs. Could be good if  you put those recomendations here    http://aurelia.io/validation/ because it could be confuse for developers that check the Aurelia documentation.
