### ISSUE TITLE
Issue with Validate-binding-behavior 'unregisterBinding' undefined

### ISSUE THREAD

**Issue by maverix** [aurelia/validation#254]
Hi All,

I just updated to the latest bits for Aurelia and have come across an issue with navigation.
When routing from one page to another I'm getting the following exception:

validate-binding-behavior.js:87 Uncaught (in promise) TypeError: binding.validationController.unregisterBinding is not a function
    at ValidateBindingBehavior.unbind (http://localhost:9000/jspm_packages/npm/aurelia-validation@0.9.0/validate-binding-behavior.js:87:36)
    at BindingBehavior.unbind (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.2.0.4/aurelia-binding.js:1265:28)
    at Binding.unbind (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.2.0.4/aurelia-binding.js:4779:31)
    at View.unbind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js:1432:23)
    at ViewFactory.returnViewToCache (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js:2295:14)
    at View.returnToCache (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js:1344:24)
    at removeAction (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js:1812:25)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js:1821:18

Relevant piece of code
https://github.com/aurelia/validation/blob/81afda4d8d03567c011efbf52b3645fa3507a94c/dist/aurelia-validation.js#L326

**Comment by jdanyow** [comment]
fixed in https://github.com/aurelia/validation/commit/ac4c7e6e8dd556bd76869a802fce33af6f4ca86d
