### ISSUE TITLE
Support custom attributes with & validate

### ISSUE THREAD

**Issue by jdanyow** [aurelia/validation#288]
@JeroenVinke commented on [Fri Jun 24 2016](https://github.com/aurelia/validatejs/issues/97)

When putting the validate binding behavior on a custom attribute's bindable variable the following error is thrown:

```
VM568 aurelia.js:20531 Uncaught (in promise) TypeError: Cannot read property 'firstChild' of null
    at ValidateBindingBehavior.getTarget (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:20531:29)
    at ValidateBindingBehavior.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:20537:25)
    at BindingBehavior.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:1880:21)
    at Binding.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:5378:31)
    at Controller.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:11864:19)
    at View.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:9955:24)
    at Controller.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:11886:19)
    at View.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:9955:24)
    at Controller.bind (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:11886:19)
    at Controller.automate (https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js:11831:12)
```

https://gist.run/?id=14ac85668b3ca27dcd8ad6d3f6579fb0/7bae372b9b6f18353f9faba700cef18581884210

---

@JeroenVinke commented on [Fri Jul 15 2016](https://github.com/aurelia/validatejs/issues/97#issuecomment-232929154)

I can create a PR with some tests for this, but i'm having a hard time getting to the element on which the custom attribute has been placed. I have access to the Controller behind the custom attribute, but the element where the attribute has been placed on isn't there as far as I can see. The [create function](https://github.com/aurelia/templating/blob/master/src/html-behavior.js#L286-L384) of the HtmlBehaviorResource has both the element and the Controller but it does not push the element onto the controller (not when it's a custom attribute that's being created). 

Is there a different way to get to the element, or should we push the element on the controller in the HtmlBehaviorResource's create function?

**Comment by jdanyow** [comment]
We may need to do some work in the templating repo to enable this. It's something we do want to support because many people create custom attributes instead of custom elements when implementing date/number/etc inputs.

**Comment by jdanyow** [comment]
potential fix: https://gist.run/?id=78bf457e85aefb7872f0670d64e21d58

**Comment by jdanyow** [comment]
re-opening- we're going to make some changes to templating to streamline this

**Comment by jdanyow** [comment]
closing via https://github.com/aurelia/validation/commit/16982e17c634d39c81d95ae644cda817df44e399
