### ISSUE TITLE
expression is not defined

### ISSUE THREAD

**Issue by jdanyow** [aurelia/validation#326]
@te-je commented on [Mon Sep 12 2016](https://github.com/aurelia/binding/issues/499)

**I'm submitting a bug report**
(wow, this is a lot of work)

* **Library Version:**
1.0.4

* **Operating System:**
Windows 10

* **Node Version:**
6.5.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.17

* **Browser:**
Chrome 53

* **Language:**
ESNext

**Current behavior:**
The following error  is raised:
```
ReferenceError: expression is not defined
    at Unparser.visitChain (http://localhost/aurelia.bundle.js:8582:33)
    at Chain.accept (http://localhost/aurelia.bundle.js:7753:20)
    at Function.unparse (http://localhost/aurelia.bundle.js:8556:16)
    at Chain.toString (http://localhost/aurelia.bundle.js:7717:21)
    at ValidationParser.parseProperty (http://localhost/aurelia.bundle.js:6491:47)
    at FluentEnsure.ensure (http://localhost/aurelia.bundle.js:13282:63)
    at Function.ValidationRules.ensure (http://localhost/aurelia.bundle.js:13322:57)
    at new StaffAdd (http://localhost/app.bundle.js:9417:40)
    at Object.invoke (http://localhost/aurelia.bundle.js:5971:12)
    at InvocationHandler.invoke (http://localhost/aurelia.bundle.js:5918:166)
    at Container.invoke (http://localhost/aurelia.bundle.js:6180:23)
    at StrategyResolver.get (http://localhost/aurelia.bundle.js:5659:35)
    at Container.get (http://localhost/aurelia.bundle.js:6117:21)
    at http://localhost/aurelia.bundle.js:4461:71
    at tryCatcher (http://localhost/aurelia-bootstrap.bundle.js:24978:23)
    at Promise._settlePromiseFromHandler (http://localhost/aurelia-bootstrap.bundle.js:22984:31)
```
This bug is triggered by aurelia-validation's use of this library and occurs for me when .matches() is used on ValidationRules. I believe the line responsible to be found here: https://github.com/aurelia/binding/blob/master/src/unparser.js#L36
That should probably be `expressions.length`.

**Comment by jdanyow** [comment]
@te-je we need more info- what is the expression in your `.ensure(???)` that's causing this error? Is there a semicolon by any chance? `;`?

**Comment by te-je** [comment]
Hi @jdanyow, there's no semicolon:

```
ValidationRules
      .ensure('3_letter_id').required().matches(/[A-Z]{3}/)
      .ensure('employee_number').required().matches(/0[0-9]{5}/)
      .on(this.item);
```

**Comment by jdanyow** [comment]
that's it! JavaScript identifiers cannot start with a number. Has to be a-z, A-Z, _ or $.

**Comment by te-je** [comment]
@jdanyow That is not an identifier. It's `this.item['3_letter_id']`. Property names *can* in fact start with a number.

**Comment by CasiOo** [comment]
I too find the line https://github.com/aurelia/binding/blob/master/src/unparser.js#L36 suspicious. Variable `expression` doesn't seem to be defined.

**Comment by jdanyow** [comment]
the parser is parsing it as if it's a standard property access (eg `foo.3_letter_id`) rather than a keyed access (eg `foo['3_letter_id']`) which is more permissive.
