### ISSUE TITLE
Validate Binding Behavior: Container is undefined 0.12.5

### ISSUE THREAD

**Issue by rfuerst87** [aurelia/validation#342]
**I'm submitting a bug report**

* **Library Version:**
0.12.5

**Please tell us about your environment:**
* **Operating System:**
Linux (Arch)

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.8

* **Aurelia CLI**
0.20.0 

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Using `validate` binding behavior with a custom element, the following error is raised:

```
vendor-bundle.js:12602 ERROR [app-router] TypeError: Cannot read property 'get' of undefined
    at ValidateBindingBehavior.getTarget (http://localhost:8080/scripts/app-bundle.js:5002:55)
    at ValidateBindingBehavior.bind (http://localhost:8080/scripts/app-bundle.js:5014:31)
    at BindingBehavior.bind (http://localhost:8080/scripts/vendor-bundle.js:5447:21)
    at Binding.bind (http://localhost:8080/scripts/vendor-bundle.js:8957:31)
    at Controller.bind (http://localhost:8080/scripts/vendor-bundle.js:20068:19)
    at View.bind (http://localhost:8080/scripts/vendor-bundle.js:18129:24)
    at Controller.bind (http://localhost:8080/scripts/vendor-bundle.js:20090:19)
    at View.bind (http://localhost:8080/scripts/vendor-bundle.js:18129:24)
    at Controller.bind (http://localhost:8080/scripts/vendor-bundle.js:20090:19)
    at Controller.automate (http://localhost:8080/scripts/vendor-bundle.js:20035:12)
    at RouterView.swap (http://localhost:8080/scripts/vendor-bundle.js:37922:38)
    at http://localhost:8080/scripts/vendor-bundle.js:15057:29
    at Array.forEach (native)
    at http://localhost:8080/scripts/vendor-bundle.js:15056:20
From previous event:
    at NavigationInstruction._commitChanges (http://localhost:8080/scripts/vendor-bundle.js:15055:33)
    at CommitChangesStep.run (http://localhost:8080/scripts/vendor-bundle.js:14904:36)
    at next (http://localhost:8080/scripts/vendor-bundle.js:14873:20)
    at iterate (http://localhost:8080/scripts/vendor-bundle.js:15958:14)
    at inspect (http://localhost:8080/scripts/vendor-bundle.js:15929:16)
    at http://localhost:8080/scripts/vendor-bundle.js:15947:24
From previous event:
    at processPotential (http://localhost:8080/scripts/vendor-bundle.js:16039:35)
    at http://localhost:8080/scripts/vendor-bundle.js:15946:18
    at iterate (http://localhost:8080/scripts/vendor-bundle.js:15950:12)
    at processActivatable (http://localhost:8080/scripts/vendor-bundle.js:15961:12)
    at ActivateNextStep.run (http://localhost:8080/scripts/vendor-bundle.js:15842:14)
    at next (http://localhost:8080/scripts/vendor-bundle.js:14873:20)
    at iterate (http://localhost:8080/scripts/vendor-bundle.js:15871:14)
    at processDeactivatable (http://localhost:8080/scripts/vendor-bundle.js:15874:12)
    at DeactivatePreviousStep.run (http://localhost:8080/scripts/vendor-bundle.js:15830:14)
    at next (http://localhost:8080/scripts/vendor-bundle.js:14873:20)
    at iterate (http://localhost:8080/scripts/vendor-bundle.js:15958:14)
    at processActivatable (http://localhost:8080/scripts/vendor-bundle.js:15961:12)
    at CanActivateNextStep.run (http://localhost:8080/scripts/vendor-bundle.js:15818:14)
From previous event:
    at LoadRouteStep.run (http://localhost:8080/scripts/vendor-bundle.js:16105:68)
    at next (http://localhost:8080/scripts/vendor-bundle.js:14873:20)
    at iterate (http://localhost:8080/scripts/vendor-bundle.js:15871:14)
    at processDeactivatable (http://localhost:8080/scripts/vendor-bundle.js:15874:12)
    at CanDeactivatePreviousStep.run (http://localhost:8080/scripts/vendor-bundle.js:15806:14)
    at next (http://localhost:8080/scripts/vendor-bundle.js:14873:20)
    at http://localhost:8080/scripts/vendor-bundle.js:15309:16
From previous event:
    at BuildNavigationPlanStep.run (http://localhost:8080/scripts/vendor-bundle.js:15307:58)
    at next (http://localhost:8080/scripts/vendor-bundle.js:14873:20)
    at Pipeline.run (http://localhost:8080/scripts/vendor-bundle.js:14886:14)
    at http://localhost:8080/scripts/vendor-bundle.js:16434:25
From previous event:
    at AppRouter._dequeueInstruction (http://localhost:8080/scripts/vendor-bundle.js:16407:32)
    at http://localhost:8080/scripts/vendor-bundle.js:16398:17
From previous event:
    at AppRouter._queueInstruction (http://localhost:8080/scripts/vendor-bundle.js:16395:14)
    at http://localhost:8080/scripts/vendor-bundle.js:16329:23
From previous event:
    at AppRouter.loadUrl (http://localhost:8080/scripts/vendor-bundle.js:16328:53)
    at BrowserHistory._loadUrl (http://localhost:8080/scripts/vendor-bundle.js:11712:55)
    at BrowserHistory._checkUrl (http://localhost:8080/scripts/vendor-bundle.js:11705:14)
```

It's probably worth to mention that in this case two custom elements are nested whereas only the "inner" element is being validated. The error occurs on [L31, validate-binding-behavior.ts](https://github.com/aurelia/validation/blob/16982e17c634d39c81d95ae644cda817df44e399/src/validate-binding-behavior.ts#L31). For some reason, `container` is undefined.

**Comment by jdanyow** [comment]
Can you confirm you have aurelia-templating [v1.1.0](https://github.com/aurelia/templating/releases/tag/1.1.0) installed?

**Comment by rfuerst87** [comment]
Thanks for the quick response. I hadn't an explicit dependency on aurelia-templating for what reason I was stuck with v1.0.1. Upgrading to v1.1.0 solved my issue. Sorry for the noise. Closing this.
